### PR TITLE
bring over improvements in fork to main repo

### PR DESCRIPTION
**Pull request by panmona**
- quest text was fixed
- font size improved

### CODE REVIEW

**Review by RohrerF — APPROVED** [review]

**Comment by panmona** [comment]
@RohrerF All tests passed but I can't merge. Do you know why?

**Comment by RohrerF** [comment]
maracuja-juice wants to merge 2 commits into stockmarkat:master from unknown repository

I guess the unknown repository is the problem

**Comment by panmona** [comment]
I merged things from unknown repositories before. So this shouldn't be the problem.

Is the travis-ci/push check required? 
The pr one passed but there's also the push check which isn't shown..

**Comment by RohrerF** [comment]
if it would be required it should be shown down there

**Comment by RohrerF** [comment]
strange i will merge it the real way :)

**Comment by panmona** [comment]
Haha :)
We have this problem on other PRs aswell

**Comment by RohrerF** [comment]
noooooo

**Comment by panmona** [comment]
As shown in #117, travis-ci/push is actually a required status.
No idea why GitHub doesn't show it on this pull request...

**Pull request merged**
